// Build-time only: the installed plugin never invokes a compiler or Wrangler.
import { execFileSync } from "node:child_process";
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL(".", import.meta.url));
const out = await mkdtemp(join(tmpdir(), "bb-shared-relay-"));
try {
  execFileSync(process.execPath, [join(root, "node_modules/wrangler/bin/wrangler.js"), "deploy", "--dry-run", "--outdir", out], { cwd: root, env: { ...process.env, WRANGLER_LOG_PATH: join(out, "wrangler.log"), WRANGLER_SEND_METRICS: "false" }, stdio: "inherit" });
  const source = await readFile(join(out, "worker.js"), "utf8");
  await writeFile(new URL("../plugin/worker-lifecycle/worker-source.generated.ts", import.meta.url), "// Generated by npm --prefix worker run build. Do not edit.\nexport const WORKER_SOURCE = " + JSON.stringify(source) + ";\n");
} finally {
  await rm(out, {recursive: true, force: true});
}
